#cloud-config
write_files:
  - content: |
      # Default server configuration
      server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }
      }
    permissions: '0750'
    path: /etc/nginx.conf.cloud_init
  - content: |
      # run certbot
      until ping -c1 ${record-fqdn} &>/dev/null; do echo "waiting for dns record to initialise" ; sleep 3 ; done
      certbot run -n --nginx --agree-tos -d ${record-fqdn}  -m ${email} --redirect
    permissions: '0750'
    path: /etc/run_certbot
runcmd:
  - until ping -c1 archive.ubuntu.com &>/dev/null; do echo "waiting for networking to initialise" ; sleep 3 ; done 
  - sudo apt-get -y update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y install certbot
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y install python3-certbot-nginx
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y install nginx
  - sudo systemctl stop nginx
  - sudo cp /etc/nginx/sites-available/default /etc/nginx.default.back.apt
  - sudo cp /etc/nginx.conf.cloud_init /etc/nginx/sites-available/default
  - sudo systemctl enable nginx
  - sudo systemctl stop nginx
  - sudo systemctl start nginx
  - sudo /etc/run_certbot
  - sudo systemctl stop nginx
  - sudo systemctl start nginx
packages_update: true
packages:
  - unzip
