#cloud-config
write_files:
  - content: |
      # Default server configuration
      server {
        listen 80 default_server;
        listen [::]:80 default_server;

     	# SSL configuration
	    #
	    listen 443 ssl default_server;
	    listen [::]:443 ssl default_server;

	    ssl_certificate /etc/letsencrypt/live/test123.georgiman.com/fullchain.pem; # managed by Certbot
	    ssl_certificate_key /etc/letsencrypt/live/test123.georgiman.com/privkey.pem; # managed by Certbot


        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }
      }
    permissions: '0750'
    path: /etc/nginx.conf.cloud_init
runcmd:
  - |
    until ping -c1 archive.ubuntu.com &>/dev/null; do echo "waiting for networking to initialise" ; sleep 3 ; done 
    export DEBIAN_FRONTEND=noninteractive
    apt-get -y update
    apt-get -y install nginx
    systemctl enable nginx
    systemctl stop nginx
    systemctl start nginx
packages_update: true
packages:
  - unzip
